# Generated by Django 3.1 on 2022-04-01 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('desc', models.TextField(blank=True, null=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('classRamaq', models.CharField(max_length=255)),
                ('studentsCount', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('academicYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='ExamEntring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEnrying', models.DateField(blank=True, null=True)),
                ('desc', models.TextField(blank=True, null=True)),
                ('academicYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
            ],
        ),
        migrations.CreateModel(
            name='ExamType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examName', models.CharField(max_length=255)),
                ('examInfo', models.TextField()),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('desc', models.TextField(blank=True, null=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentId', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('gender', models.CharField(default='Male', max_length=10)),
                ('image', models.ImageField(blank=True, null=True, upload_to='students')),
                ('name', models.CharField(max_length=255)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('masuulkaName', models.CharField(blank=True, max_length=255, null=True)),
                ('masuulkaNumber', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('dateModified', models.DateTimeField(auto_now=True)),
                ('accessedClasses', models.ManyToManyField(related_name='accessedClasses', to='api.Classe')),
                ('stdARegistredAcademicYear', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.academicyear')),
                ('stdClass', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resutPercentage', models.CharField(blank=True, max_length=255, null=True)),
                ('resultSum', models.IntegerField(blank=True, null=True)),
                ('resutlStatus', models.BooleanField(default=True)),
                ('examId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examentring')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('theExamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examentring')),
            ],
        ),
        migrations.AddField(
            model_name='examentring',
            name='examType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examtype'),
        ),
        migrations.AddField(
            model_name='classe',
            name='subjects',
            field=models.ManyToManyField(blank=True, to='api.Subject'),
        ),
    ]
