# Generated by Django 3.1 on 2022-04-05 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='stdClasse',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.classe'),
            preserve_default=False,
        ),
    ]
