# Generated by Django 3.1 on 2022-04-09 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_marks_stdclasse'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='image',
        ),
    ]
