# Generated by Django 3.1 on 2022-04-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_student_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='masuulkaNumber',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
