# Generated by Django 3.1 on 2022-04-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220411_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='isCurrentAcademicYear',
            field=models.BooleanField(default=False),
        ),
    ]
