# Generated by Django 3.1 on 2022-04-19 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_examentringfiles'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarksTemp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.IntegerField(default=0)),
                ('stdClasse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.classe')),
                ('studentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('subjectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.subject')),
                ('theExamId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.examentring')),
            ],
        ),
    ]
